# Generated by Django 3.2.5 on 2023-02-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_tabpermutation_roomtabsequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TabContentItem',
            new_name='RoomTabItem',
        ),
    ]
