# Generated by Django 3.2.5 on 2023-02-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_tabcontentitem_roomtabitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtabitem',
            old_name='tab_content_id',
            new_name='room_tab',
        ),
    ]
