# Generated by Django 3.2.5 on 2023-02-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_tab_content_id_roomtabitem_room_tab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content1',
            new_name='tab1',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content10',
            new_name='tab10',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content2',
            new_name='tab2',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content3',
            new_name='tab3',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content4',
            new_name='tab4',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content5',
            new_name='tab5',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content6',
            new_name='tab6',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content7',
            new_name='tab7',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content8',
            new_name='tab8',
        ),
        migrations.RenameField(
            model_name='roomtabsequence',
            old_name='tab_content9',
            new_name='tab9',
        ),
    ]
