# Generated by Django 3.2.5 on 2023-02-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230217_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab1', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab10', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab2', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab3', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab4', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab5', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab6', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab7', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab8', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab9', to='base.roomtab'),
        ),
    ]
