# Generated by Django 3.2.5 on 2023-02-23 09:14

import base.models.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230217_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.CharField(default=base.models.functions.create_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('web', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('zip_code', models.CharField(blank=True, default='', max_length=7)),
                ('state', models.CharField(blank=True, default='', max_length=15)),
                ('city', models.CharField(blank=True, default='', max_length=15)),
                ('address_1', models.CharField(blank=True, default='', max_length=15)),
                ('address_2', models.CharField(blank=True, default='', max_length=15)),
                ('mon', models.CharField(blank=True, default='', max_length=15)),
                ('tue', models.CharField(blank=True, default='', max_length=15)),
                ('wed', models.CharField(blank=True, default='', max_length=15)),
                ('thu', models.CharField(blank=True, default='', max_length=15)),
                ('fri', models.CharField(blank=True, default='', max_length=15)),
                ('sat', models.CharField(blank=True, default='', max_length=15)),
                ('sun', models.CharField(blank=True, default='', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.personal'),
        ),
    ]
