# Generated by Django 3.2.5 on 2023-02-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230223_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='wed',
        ),
        migrations.AddField(
            model_name='personal',
            name='fri_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='fri_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='mon_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='mon_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='sat_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='sat_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='sun_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='sun_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='thu_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='thu_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='tue_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='tue_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='wed_from',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='personal',
            name='wed_to',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='personal',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
