# Generated by Django 3.2.5 on 2023-02-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230225_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag10',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag6',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag7',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag8',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag9',
        ),
        migrations.AddField(
            model_name='post',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag1', to='base.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag2', to='base.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag3', to='base.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag4', to='base.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag5', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag1', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag10', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag2', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag3', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag4', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag5', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag6', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag7', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag8', to='base.tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_tag9', to='base.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
