# Generated by Django 3.2.5 on 2023-02-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_tag_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag1', to='base.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag2', to='base.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag3', to='base.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag4', to='base.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag5', to='base.tag'),
        ),
    ]
