# Generated by Django 3.2.5 on 2023-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_tag_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=15),
        ),
    ]
