# Generated by Django 3.2.5 on 2023-03-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_tag_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique_title_user',
        ),
    ]
