# Generated by Django 3.2.5 on 2023-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_room_unique_title_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expansion',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='expansion',
        ),
        migrations.RemoveField(
            model_name='replyreply',
            name='expansion',
        ),
        migrations.AddField(
            model_name='post',
            name='agree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='disagree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='false_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='true_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replypost',
            name='agree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replypost',
            name='disagree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replypost',
            name='false_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replypost',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replypost',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replypost',
            name='true_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyreply',
            name='agree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyreply',
            name='disagree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyreply',
            name='false_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyreply',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyreply',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyreply',
            name='true_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ObjectExpansion',
        ),
    ]
