# Generated by Django 3.2.5 on 2023-03-02 14:05

import base.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230302_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.post_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.post_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.post_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.post_directory_path),
        ),
        migrations.DeleteModel(
            name='PostImgs',
        ),
    ]
