# Generated by Django 3.2.5 on 2023-03-02 14:33

import base.models.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20230302_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.room_directory_path),
        ),
        migrations.AddField(
            model_name='room',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.room_directory_path),
        ),
        migrations.AddField(
            model_name='room',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.room_directory_path),
        ),
        migrations.AddField(
            model_name='room',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.room_directory_path),
        ),
        migrations.AddField(
            model_name='room',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.functions.room_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_tag1', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_tag2', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_tag3', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_tag4', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_tag5', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tag1', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tag2', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tag3', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tag4', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tag5', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.roomauthority'),
        ),
        migrations.AlterField(
            model_name='room',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.personal'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag1', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag10', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag2', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag3', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag4', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag5', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag6', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag7', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag8', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tag9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_tag9', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab1', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab10', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab2', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab3', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab4', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab5', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab6', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab7', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab8', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomtabsequence',
            name='tab9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab9', to='base.roomtab'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='authority',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='base.roomauthority'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='RoomImgs',
        ),
    ]
