# Generated by Django 3.2.5 on 2023-03-10 14:53

import base.models.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20230302_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag10',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag6',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag7',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag8',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag9',
        ),
        migrations.RemoveField(
            model_name='roomreplytype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roomreplytype',
            name='is_deleted',
        ),
        migrations.CreateModel(
            name='TagSequence',
            fields=[
                ('id', models.CharField(default=base.models.functions.create_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag1', to='base.tag')),
                ('tag10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag10', to='base.tag')),
                ('tag2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag2', to='base.tag')),
                ('tag3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag3', to='base.tag')),
                ('tag4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag4', to='base.tag')),
                ('tag5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag5', to='base.tag')),
                ('tag6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag6', to='base.tag')),
                ('tag7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag7', to='base.tag')),
                ('tag8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag8', to='base.tag')),
                ('tag9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag9', to='base.tag')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag_sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tagsequence'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag_sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tagsequence'),
        ),
        migrations.AddField(
            model_name='room',
            name='tag_sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tagsequence'),
        ),
    ]
