# Generated by Django 3.2.5 on 2023-03-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20230310_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_accounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replypost',
            name='is_accounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
