# Generated by Django 3.2.5 on 2023-03-12 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20230311_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreplytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomreplytype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
