# Generated by Django 3.2.5 on 2023-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20230319_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='embed_video',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
