# Generated by Django 3.2.5 on 2023-03-26 06:11

import base.models.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_room_embed_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='embed_video',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RoomLink',
            fields=[
                ('id', models.CharField(default=base.models.functions.create_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to=base.models.functions.room_directory_path)),
                ('link', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
    ]
